---
- name: firewall | Install Firewalld
  yum:
    name: firewalld
    state: present

- name: firewall | Enable and Start Firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: firewall | Enable ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - "{{ firewall_ports }}"
