---

- name: Update satellite node
  package:
    name: '*'
    state: present
  tags:
    - install_satellite

- name: Install Satellite Package
  package:
    name: satellite-{{ satellite_version }}*.el7*
    state: present
  async: 3600
  poll: 60
  tags:
    - install_satellite

####### Satellite Post Installation Tasks ###############
- name: Satellite Post-installation tasks file only first match
  include_tasks: "{{ item }}"
  loop: "{{ query( 'first_found', satellite_post_installation_task_files | d('/no/file/provided') , errors='ignore') }}"
  tags:
    - install_satellite

####### Satellite Pre Configuration Tasks ###############
- name: Satellite Pre-configuration tasks file only first match
  include_tasks: "{{ item }}"
  loop: "{{ query( 'first_found', satellite_pre_configuration_task_files | d('/no/file/provided') , errors='ignore') }}"
  tags:
    - configure_satellite

########### Satellite Configuration ########
- name: configure satellite
  command: >-
    satellite-installer
    {% if '--scenario' not in satellite_arguments %} --scenario satellite{% endif %}
    {% if '-admin-username' not in satellite_arguments %}
    {% if satellite_version is version('6.4', '<=') %} --foreman-admin-username {{ satellite_admin | default('admin') }}
    {% else %} --foreman-initial-admin-username {{ satellite_admin | default('admin') }}{% endif %}
    {% endif %}
    {% if '-admin-password' not in satellite_arguments %}
    {% if satellite_version is version('6.4', '<=') %} --foreman-admin-password {{ satellite_admin_password }}
    {% else %} --foreman-initial-admin-password {{ satellite_admin_password }}{% endif %}
    {% endif %}
    {% if 'certs-cname' not in satellite_arguments %} --certs-cname {{ inventory_hostname }}{% endif %}
    {% if satellite_arguments is defined %}
    {% for satellite_arguments in satellite_arguments %}
    {{ satellite_arguments }}
    {% endfor %}
    {% endif %}
  register: command_output
  changed_when: 'command_output.rc == 0'
  async: 3600
  poll: 60
  tags:
    - install_satellite
